### ISSUE TITLE
`/setProhibitMotionOnHomeSw` not disabling movement; poor homing operation

### ISSUE THREAD

**Issue by JulianOrteil** [ponoor/step-series-support#10]
@kanta 

I am currently running a 23HS5628-8 motor from Hanpose on the STEP400 (no other motors attached). I have encountered an issue with the motor continuing to move in the direction of home even with the home switch activated. I have run `/setProhibitMotionOnHomeSw`, and verified it is being properly set through `/getProhibitMotionOnHomeSw`, so I'm unsure if this is a configuration error on my end or an issue in the firmware.

Also, homing is overly "rough" for this motor. Lots of vibration and noise. Curiously, running `/goTo` results in a smooth, quiet operation. I currently have a 24V supply running the board with the motor configured using the defaults here: https://github.com/ponoor/step-series-support/blob/main/configGenerator/step400-configs/STEP400_23HS5628_24V.json

Note: I have increased my kval params to 14 75 75 75 versus the 14 27 27 27 defaults that you have. My params are MUCH quieter and smoother.

**Comment by JulianOrteil** [comment]
Clarification:

My KVAL params:
```
kvalHold: 14
kvalRun: 75
kvalAcc: 75
kvalDec: 75
```
I can also send you video of what I am encountering if you so wish.

**Comment by kanta** [comment]
@JulianOrteil Thanks for the report!

`/setProhibitMotionOnHomeSw` works fine in my environment. 
Did you test the command right after homing procedure? If so, the home switch might not activated, because the homing will end up at just outside of the sensor activated area. Possibly you can verified the home switch state with `/getHomeSw` before the test.

`/setHomeSwMode 1 0` will be useful when there is a dead end in the motor's working range. 
https://ponoor.com/docs/step-series/osc-command-reference/home-limit-sensors/#sethomeswmode_intmotorid_boolsw_mode

Please make sure the motor driver is in HiZ state when you send this command.

I will check and come back for the homing motor motion thing later!

**Comment by kanta** [comment]
I realized that my 23HS5628 are no longer in my hand because they have been embedded into something. So I was not able to experiment with the identical motor, but I think this is probably the same problem of #7. It seems much bigger KVAL values are required for very slow motion. 
Is the same problem happen if you drive the motor by `/run` with the same speed?
One option is test bigger KVAL, and another option is to use higher speed for homing, as long as there is no problem for the homing switch.

[BEMF parameters](https://ponoor.com/en/docs/step-series/osc-command-reference/voltage-and-current-mode-settings/) are to compensate KVALs according to the rotation speed, and these values in config files are calculated according to the application note [PDF](https://www.st.com/resource/en/application_note/an4144-voltage-mode-control-operation-and-parameter-optimization-stmicroelectronics.pdf) from STM. However, I have realized that things do not work as calculated in reality...

**Comment by JulianOrteil** [comment]
> @JulianOrteil Thanks for the report!
> 
> `/setProhibitMotionOnHomeSw` works fine in my environment. Did you test the command right after homing procedure? If so, the home switch might not activated, because the homing will end up at just outside of the sensor activated area. Possibly you can verified the home switch state with `/getHomeSw` before the test.
> 
> `/setHomeSwMode 1 0` will be useful when there is a dead end in the motor's working range. https://ponoor.com/docs/step-series/osc-command-reference/home-limit-sensors/#sethomeswmode_intmotorid_boolsw_mode
> 
> Please make sure the motor driver is in HiZ state when you send this command.
> 
> I will check and come back for the homing motor motion thing later!

@kanta It appears I sent `/setHomeSwMode 1 1`; thank you for pointing that out. This appears to be working now.

As for homing, homing the motor in current mode is much quieter and smoother than voltage mode.



> It seems much bigger KVAL values are required for very slow motion. Is the same problem happen if you drive the motor by /run with the same speed?

Running the motor in voltage mode with your defaults or my KVALs using the `/goTo` or `/run` command at slow speeds is not showing the same behavior as `/homing` does.

> One option is test bigger KVAL, and another option is to use higher speed for homing, as long as there is no problem for the homing switch.

Running higher homing speeds makes the issue worse with voltage mode enabled.



> [BEMF parameters](https://ponoor.com/en/docs/step-series/osc-command-reference/voltage-and-current-mode-settings/) are to compensate KVALs according to the rotation speed, and these values in config files are calculated according to the application note [PDF](https://www.st.com/resource/en/application_note/an4144-voltage-mode-control-operation-and-parameter-optimization-stmicroelectronics.pdf) from STM.

Does BEMF also compensate for current mode (the PDF appears to say BEMF only applies to voltage mode)? I am most likely going to run the motor in current mode as my application doesn't require high precision (even 10 full steps off is perfectly acceptable) but does need to run faster than the 620 steps/s maximum voltage mode allows.


Then one final question: without any load, I am able to run the NEMA23 at over 11,000 RPM like in your video comparing voltage vs current mode. Attached to a lead screw that will have no more than 5kgs of effective mass, do I need to re-tune  TVAL/BEMF? I ask because I can't reliably run the motor (using default TVAL and BEMF params from your example config) at more than 2000 steps/s without it locking up and "screaming" (again, like in your video when that motor locks up).

Thanks,
Jules

**Comment by kanta** [comment]
@JulianOrteil Glad to hear the home switch is now working fine.

I walked through the homing code again but I didn't find any special things, it should be same motion as `/run`. Also tested with a physical NEMA23 motor and I couldn't find differences between both motion `/run` and `/homing`. Could you send a video to see more details? 

BEMF compensation only works for the voltage mode. This function attempts to keep the phase current constant by varying the voltage applied to the motor (open loop). In the current drive mode, the phase current is controlled to be constant with current detecting resisters (closed loop).

When you add a load to a motor, the required torque and the mechanical resonances will be changed so usually need to tune parameters again. If you want the motor to rotate at high speed, you will often need to increase the power supply voltage. You can consider to apply 48V, or more. Sometimes I use 72V (24Vx3) to get a high winding speed.

**Comment by JulianOrteil** [comment]
@kanta Thank you for your explanations and detail!

My apologies for asking so many questions and encountering newbie issues. I am used to DC motors which behave quite differently than steppers, so that's my only excuse :stuck_out_tongue: 

I upped the voltage to 48V (my supply only goes up that high) and virtually all of these issues are gone, including those homing vibrations and noise. I'll close the ticket now, but thank you for your help :)

Jules

**Comment by kanta** [comment]
Great! Though some mysteries are left...
Yes, stepper motors are quite different from DC motors and sometimes not intuitive. 
Questions are always welcome! It's a good chance to improve the docs and I'd be happy if my past experiences with struggles could help someone else.
